name: Deploy GH Pages

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # - run: cd

            - name: Deploy react app to github pages
              uses: ./.github/actions/deploy-react-action
              env:
                  CLIENT_DIR: ./MelbourneAttractionsProject/ClientApp/
